import './sass/main.scss';
import './js/refs.js';
import './js/loadMoreBtn.js';
import './js/apiService.js';
import './templates/';
import './js/updateMarkupGallery';
import './js/loadMoreBtn.js';
import './js/homePage.js';
import './js/4filmDetailsPage.js';
